{% set version = '0.0-3' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-assertive.sets
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/assertive.sets_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/assertive.sets/assertive.sets_{{ version }}.tar.gz
  sha256: 876975a16ed911ea1ad12da284111c6eada6abfc0118585033abc0edb5801bb3

build:
  number: 1006
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-assertive.base >=0.0_7
  run:
    - r-base
    - r-assertive.base >=0.0_7

test:
  commands:
    - $R -e "library('assertive.sets')"           # [not win]
    - "\"%R%\" -e \"library('assertive.sets')\""  # [win]

about:
  home: https://bitbucket.org/richierocks/assertive.sets
  license: GPL-3.0-or-later
  summary: A set of predicates and assertions for checking the properties of sets.  This is mainly
    for use by other package developers who want to include run-time testing features
    in their own packages.  End-users will usually want to use assertive directly.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - jenzopr
