travis:
  secure:
    BINSTAR_TOKEN: v5mel/Qf/NKvk5JyEC3FTI0/r5I4y5+IGBMt6Rhs7neiEgL6VZiZ0p/knutEOQsfEtF7VNO9oGEMz9p2J8R0UheMAGGL0R4x4a4VRq3mp23GlaLTeaOlShHvOW7/E4Ma4++5AR2g0vMBI+s3Ic4UgdF5HLC8mBA4XEiPZw58bGUwfNjoVxfNiCtL4GmH2h5R3Iy4DoEUW751X3vTpKoHSiYAljo4sqWmgCW+18JFivLy89kt6Ko9y7OqQkI6aRSRTTPD1L+jS1YRdtXz62gBTOH0vSW0woE/PjdPqbDpBcVGkgU0tiq8SPUngZHupaJ5Ui4/ImHf6o1h7xpDhdFjLI6snuyM1aMBfKN5t/ZlS2q+m7k/oQxhpMF8nYnV4eAwBK9hED52oxXNa9iRdo6stK2PQ9WGW8v398mv1qko9cqMuydEntW4I4qK7P60LcOyk4NNSSZycTOPjd+7AUMOHaMwt/wsEyZLXvYktx3lyhOsePUy7DgYizzMj93zHULSQNgO7RWqaBkjUgf+GblS5o6cV7IEdTYfVkgUoOkDUTCoj57En2JIumtZyUjSPbQebKSkvUxZvMni9d50AIRTEZDw1bG5Fi3S7q88vgav2hqTF9b+rdZLSI2F46FZb/NPJqZ4ITwNJ+waZ2rVLDuEHMonnKJJ9I9heX+1RLxQcZs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
