travis:
  secure:
    BINSTAR_TOKEN: PyYRn7ZgTZWoFtVgXeHK/lnIfXHS3trJDgcYNShIjbjXlFoBGLcsjs5CzJL9NUVH95/3Hgk2TVlErz336mdwjHpV7cqUppwX6BTUIxMUW5nQTi0/ziWtrobR3Sk1xBY90G6i7wAylPx0HeCXK4963+2lV9WvnOB0cDRmu2qPJMj174Mm/JYnL/GzDx3Zns3tdfpE5hIeMSh6sBtsPJSMnP+zTXmoq6Cyn7azVU+X1hhWo3Hqb4jqkcyF2Iru+6qdUmhVezGi/eaauAhDxV3v5zsmm3IlXWKpsQ8TQxjw3DXzFHYK8Ww0FFlTrDXfEN3oRn8Nvx+8GB7xi96WLkqJ2+V93I8Wg46FzuPcve6wsOh9dmrz9zPpAhaJrST6qe/f/vTF44CLNTmw5ntilIUyw/iO/o1W+kWaigCdp+PEtMwP3KBQZm9ASCwLhJR8I+vkEndug6SXsJTfFXcHakoIJyJKxHATCqFr8NzzQ73m+xCtO64kDfyHQeqzRYcSXeiNkwLIaIia5WhYW9fmuUl1mp+dGOVMyDQ4uCzlFoR4cTK9Jg38nEHTe8imFgZEtOq9ydxdtuHFCQP8jwn94y2SyxZhf5t+Yjia47MAD44leMN++yzHdzGykOiNUG+3pj4LQK1Ey6BQfOcYPymMPloZb9rIXLBi9QHNpO7g1zTdNaA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
