travis:
  secure:
    BINSTAR_TOKEN: pWVlcT9cdsF2IX9EMuwInqIb9pVt+J+vJFktoheyV5VoiZ7Wfju73mwFHdjBox3h9PgSv8dhWsJrnRgTRFo5JoQkC7N4yZNVWPccKsh4MQIgoQAoK/j7F/Y/89zSAi48SFOkhdlefCAFpSQYgf6/kwiHUGCdNTkykmtoXCOxfYL93T7dMAFfm97UgVpROVQP//TLit0lxm8KJuR8Lyr1zym1JIanU0HC/l9agxqQKSrXcyAEIAdXbsuSLGJCVUxb1u8aTiC/CO5pYbjrVSWCKoOBzDlqpIL9eliKDO6QjdD/4jAPr+IupUCcCGk9FtK4NdX6iZmb+LOQIeWz64m/8rVJifLXgcajqT5Y5TqtWCjSM8qvfvWVfVXaRsaLfQgg1xy0byaTbexhIp2vZdMEYSW/OH+aCl8mbX+7vAC9mOhhe7JayoFDXmx+tY1thRUzILNepETFiU5bS6OMJMA4HqVrY5KMrP9A5tvo5DyCbG4RBOn+VU1cBPwPpam4Hlc2rZaX38Qu0FO11m79hNbKD2nvu9quXUodB4OK/mVV2xsw0CPrz81cXqnrrFsL9MjUU4iJYB4FmzYiHIjPrnyuI8ecChYw2NY9JZwdWN8icvqsVAY+7wLNsJ4EXYdlBXVJBrNmr85wZvkCRpSWhoZruPOV2zkvNmyff8dZms7vQOI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
