appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: HeuCZmKVg6jwR9OHsAlyLYDf6+h6g3zmF4+gj2DO78Xch+Pf2sCMe66SPj6wi4kAojg1qbcRPZwy6fgFx5KPBa3KDYgnIukNLFEnkA8HhetupBAq2GXTkcOVrSjC0DF3If9buKyDLJqPBWGJBDvEk0AJGx2lpNGW3SaCWb65aLVlYzAqrwQkke5fF5hLE2i//6sAPojR97Cps8W35ttA2sVM5jBSAB/0eDbvLkALVKad1BATHv278xL4ZSRZHEM9DGZBT5VrHAj9FSSjcJNWYKto8K5aozTcfWnk/uyrldoIMB+FQqD9/eh7pnG4L8nGKioJ1TPulBWFGpJVWd6PJchowT7DxX4zDdeGKgvy+WUP2cBzVNnnNgeVFKky3Fzaq9NCV2NqV39DJHSzNuFh7xbpSGBXDZCuTKC0eWGK2xdrGHGIY4SD1WAIMgcp5wrN8ephS5KblE/i+sf5OIhdc7IqbCfAPcPaNlm51oM164aL/Kdou+7Nm17duN/uQYD9xi1o7LGkW5sM8lQfuAHCUk9x4VOlUPBhkiJlyFAj1FXwq+iE0zIVu5+mxthDUNCWO9PCmNizvz7y/o5CLPpoBZ0aEd7YS1H9FXYMMRXjcbR+ml9unDkLAXUUgaCSfcK13zkWqyD8bIaz3zpbut2SSa2sFLsXi6QW/yk9w3CgXk4=}
bot:
  automerge: true
